### ISSUE TITLE
failed to execute spifalsh-read/write on A20

### ISSUE THREAD

**Issue by andyshrk** [linux-sunxi/sunxi-tools#120]
when execute sunxi-fel  spiflash-info/spiflash-read/spiflash-write for A20, noting happen on the console,
missing setting pinmux ?

**Comment by plaes** [comment]
See pull #119

**Comment by andyshrk** [comment]
> See pull #119

Still didn't been pulled in?

**Comment by wens** [comment]
Pulled.

**Comment by andyshrk** [comment]
tks
