### ISSUE TITLE
sunxi pio library

### ISSUE THREAD

**Issue by xloem** [linux-sunxi/sunxi-tools#121]
It seems all the gpio code available around the internet re-implements what's necessary.  It would be nice to have a library file for GPIO that other code could reuse.  Would this project be the right place to provide this?

**Comment by wens** [comment]
Even if it were, it would be a separate repo.

Unlike the Raspberry Pi, there is no fixed arrangement for GPIO headers.
The most you would share is probably the GPIO kernel interfacing code,
and some code for converting pin names into GPIO numbers.
