### ISSUE TITLE
AllwinnerH6出错usb_bulk_send() ERROR -9: Pipe error

### ISSUE THREAD

**Issue by fbia1232000** [linux-sunxi/sunxi-tools#126]
E:\Allwinner\sunxi-tools-1.4.2>sunxi-fel -p uboot u-boot-sunxi-with-spl.bin write 0xa000000
Warning: no 'soc_sram_info' data for your SoC (id=1728)
usb_bulk_send() ERROR -9: Pipe error

E:\Allwinner\sunxi-tools-1.4.2>sunxi-fel spl u-boot-sunxi-with-spl.bin write 0xa00000000
usb_bulk_send() ERROR -7: Operation timed out

**Comment by wens** [comment]
H6 supported with #109 and commit ed54b135c1968d8b9a9bf2edfa9b0b28d34bb92f.
