### ISSUE TITLE
meminfo.c:25:10: fatal error: sys/io.h: No such file or directory    25 | #include <sys/io.h>

### ISSUE THREAD

**Issue by heldiho53** [linux-sunxi/sunxi-tools#137]
Cannot build target tools. Header files seem to be missing. What to do here? I'm compiling with linaro4.9 as recommended by the sunxi wiki.

**Comment by jake5253** [comment]
try cross_compile= <this toolchain> https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/

**Comment by apritzel** [comment]
Probably the same as #144. Should be fixed with https://github.com/linux-sunxi/sunxi-tools/commit/783cbd59fcf086a9aaf603271823fb4ca71f0c55 (already merged).
@heldiho53 please retry with the latest HEAD and close, if it works now. Thanks!
