### ISSUE TITLE
exec 'sunxi-fel spiflash-info' can't not find nor flash

### ISSUE THREAD

**Issue by haorongLemon** [linux-sunxi/sunxi-tools#143]
when i exec "sunxi-fel spiflash-info" command, i got "No SPI flash detected."
i almost change nor flash  in my board(orange pi zero)
finnally, i find the gpio base address is not correct.

file: fel-spiflash.c
static uint32_t gpio_base(feldev_handle *dev)
{
	soc_info_t *soc_info = dev->soc_info;
	switch (soc_info->soc_id) {
	case 0x1817: /* V831 */
		return 0x0300B000;
	default:
		return 0x01C28000;   // error here, the PORT base addr is 0x01C20800, not 0x01C28000!
	}
}

after changing that, it works!

**Comment by ewoutp** [comment]
I can confirm that this fix works on my OrangePiZero
