### ISSUE TITLE
error in make (fatal error: linux/libfdt.h: No such file or directory)

### ISSUE THREAD

**Issue by MahdadGhasemian** [linux-sunxi/sunxi-tools#157]
os: ubuntu v20.04
sunxi-tools v1.4
$ make
cc -std=c99 -Wall -Wextra -Wno-unused-result -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE -D_DEFAULT_SOURCE -Iinclude/  `pkg-config --cflags libusb-1.0` `pkg-config --cflags zlib`  -o sunxi-fel \
	fel.c fit_image.c progress.c soc_info.c fel_lib.c fel-spiflash.c  `pkg-config --libs libusb-1.0` `pkg-config --libs zlib` -lfdt
fit_image.c:20:10: fatal error: linux/libfdt.h: No such file or directory
   20 | #include <linux/libfdt.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:141: sunxi-fel] Error 1

**Comment by MahdadGhasemian** [comment]
Hi

I installed it by package and it work. :

`sudo apt install sunxi-tools`

**Comment by zxc503** [comment]
sudo apt-get install libfdt-dev

**Comment by giuliobenetti** [comment]
@MahdadGhasemian since this issue is resolved you should close it.

**Comment by artlog** [comment]
This information should be propagated here : https://linux-sunxi.org/Sunxi-tools#Building_from_Source
