### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by theofficialgman** [linux-sunxi/sunxi-tools#183]
I didn't have another way of contacting the developers. Your website [linux-sunxi.org/](http://linux-sunxi.org/) is currently down and has been for the past few days.

**Comment by apritzel** [comment]
Hi @theofficialgman, we use the #linux-sunxi IRC channel on OFTC for those kind of communication, and it was reported there already around the same time. It apparently wasn't simple to fix, but as you might have noticed, it's now back up again.
Thanks for the report!
